version: 2
project_name: ec2-spot-interrupter
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/main.go
    ldflags:
      - -s -w -X main.build={{.Version}} -X main.commit={{.Commit}} -X main.builtBy=goreleaser
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_arm64
      - darwin_amd64
    binary: ec2-spot-interrupter
archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
homebrew_casks:
  - name: ec2-spot-interrupter
    directory: Casks
    homepage: "https://github.com/aws/amazon-ec2-spot-interrupter"
    description: "A simple CLI tool that triggers Amazon EC2 Spot Interruption Notifications and Rebalance Recommendations."
    license: "Apache-2.0"
    caveats: "ec2-spot-interrupter --interactive"
    repository:
      owner: aws
      name: homebrew-tap
      branch: "{{ .ProjectName }}-{{.Version}}"
      token: "{{ .Env.EC2_BOT_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: aws
          name: homebrew-tap
          branch: main
